services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rocketscience_app
    volumes:
      - .:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: rocketscience_nginx
    ports:
      - "${APP_PORT:-8088}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:14-alpine
    container_name: rocketscience_postgres
    restart: always
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
